export const HOME_MOCK_DASHBOARD = {
  generated_at: '2026-05-13T14:00:00.000Z',
  unit_assumption_pct: 2,
  status: 'tracking_results',
  source: 'mock',
  overall: {
    decisions: 34,
    complete: 27,
    pending: 7,
    correct: 16,
    incorrect: 11,
    accuracy: 59.26,
    profit_loss_proxy: 4.2,
    estimated_roi_pct: 8.4,
  },
  performance_windows: [
    {
      key: 'today',
      label: 'Today',
      span: '1D',
      accuracy: 63.64,
      roi_pct: 3.8,
      sample_size: 11,
      complete: 9,
      pending: 2,
      note: 'Most recent execution window.',
    },
    {
      key: '7d',
      label: '7D',
      span: '7D',
      accuracy: 61.11,
      roi_pct: 5.1,
      sample_size: 18,
      complete: 15,
      pending: 3,
      note: 'Short rolling context.',
    },
    {
      key: '30d',
      label: '30D',
      span: '30D',
      accuracy: 58.82,
      roi_pct: 8.4,
      sample_size: 34,
      complete: 27,
      pending: 7,
      note: 'Current operating window.',
    },
    {
      key: 'season',
      label: 'Season',
      span: 'SZN',
      accuracy: 56.25,
      roi_pct: 11.9,
      sample_size: 48,
      complete: 40,
      pending: 8,
      note: 'Broader sample for magnitude.',
    },
    {
      key: 'last-season',
      label: 'Last Season',
      span: 'LY',
      accuracy: 54.8,
      roi_pct: 14.2,
      sample_size: 162,
      complete: 147,
      pending: 15,
      note: 'Historical baseline for long-horizon context.',
    },
  ],
  primary_allocation: {
    label: 'High Signal',
    decisions: 9,
    complete: 8,
    pending: 1,
    correct: 6,
    incorrect: 2,
    accuracy: 66.67,
    profit_loss_proxy: 3.8,
    estimated_roi_pct: 7.6,
  },
  high_conviction: {
    label: 'Elite + High Conviction',
    decisions: 12,
    complete: 10,
    pending: 2,
    correct: 7,
    incorrect: 3,
    accuracy: 70,
    profit_loss_proxy: 2.9,
    estimated_roi_pct: 5.8,
  },
  sample_size: 34,
  complete_outcomes: 27,
  pending_outcomes: 7,
  realized_roi_pct: 8.4,
  trust: {
    ledger_coverage: 100,
    contract_validation: 'passed',
    learning_status: 'learning',
    policy_feedback_status: 'available',
    recommendation_count: 2,
  },
};
